# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10

platform:
  - x86

# scripts that run after cloning repository
install:
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version

before_test:
  - echo Before tests!

# to run your custom scripts instead of automatic tests
test_script:
  - cmd: npm run appveyor

after_test:
  - ps: ./ci/appveyor.ps1

artifacts:
  - path: tests.json

build: OFF
deploy: OFF
