# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.11

platform:
  - x64
  - x86

install:
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version
  - npm run ci-test

build: OFF
test: OFF
deploy: OFF
