# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10

platform:
  - x86

# scripts that run after cloning repository
install:
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version

# to run your custom scripts instead of automatic tests
test_script:
  - npm run appveyor

build: OFF
deploy: OFF
